### ISSUE TITLE
[Operative] Projekt-Setup

### ISSUE THREAD

**Issue by MK2112** [HWR-Berlin-SWE-II-Gruppe-2-Team-3-2022/Dokumentation#1]
## Description

Moving files of old project state around in order for them to remain accessible but not hindering/confusing while work continues.

### Tasks
- [x] Archive old presentations
- [x] Setup new Milestones and respective objectives
- [x] Setup Labels
- [x] Import GitHub Actions Workflow
- [x] IEEE Paper Template importieren
- [x] Automated generation of PDF file resulting from IEEE template Latex
