### ISSUE TITLE
[Documentation] Themeneinreichung, Mitteilung zu Projektmitgliedern

### ISSUE THREAD

**Issue by MK2112** [HWR-Berlin-SWE-II-Gruppe-2-Team-3-2022/Dokumentation#7]
## Detailed Description
Das Thema des Kursprojektes sowie die Namen der beteiligten Teammitglieder in Form einer .txt-Datei zusammenfassen.
Wir packen da noch zusätzlich eine kleine Beschreibung rein, was Genderly macht und was wir an Erweiterungen planen. Schadet nicht und haben wir ja schon mit #6 erarbeitet.

### Tasks
- [x] .txt mit Projekttitel und Projektmitgliedern erstellen
- [x] Kurze Beschreibung der Funktionalität hinzufügen
- [x] Kurze Beschreibung der geplanten, neuen Features hinzufügen
